// AUTO-GENERATED by scripts/gen-reverse-index.mjs — DO NOT EDIT.
// Reverse index: vocab word → tutorial example sentences that reference it.
// Regenerated on every `pnpm build` / `pnpm dev`.

import type { ExampleRef } from "./types";

export const REVERSE_INDEX: Record<string, ExampleRef[]> = {
  "aimer": [
    {
      "chapterId": "e02",
      "chapterTitleEn": "The present tense of -er verbs",
      "chapterTitleZh": "-er 动词的现在时",
      "pointTitleEn": "Stem + ending: je parle, nous parlons",
      "pointTitleZh": "词干 + 词尾：je parle，nous parlons",
      "anchor": "ex-e02-e02-1-1",
      "fr": "Nous aimons le café."
    },
    {
      "chapterId": "e02",
      "chapterTitleEn": "The present tense of -er verbs",
      "chapterTitleZh": "-er 动词的现在时",
      "pointTitleEn": "j' before a vowel",
      "pointTitleZh": "元音前的 j'",
      "anchor": "ex-e02-e02-2-0",
      "fr": "J'aime le chat."
    },
    {
      "chapterId": "e02",
      "chapterTitleEn": "The present tense of -er verbs",
      "chapterTitleZh": "-er 动词的现在时",
      "pointTitleEn": "Negation: ne … pas",
      "pointTitleZh": "否定：ne … pas",
      "anchor": "ex-e02-e02-3-1",
      "fr": "Il n'aime pas le café."
    }
  ],
  "café": [
    {
      "chapterId": "e02",
      "chapterTitleEn": "The present tense of -er verbs",
      "chapterTitleZh": "-er 动词的现在时",
      "pointTitleEn": "Stem + ending: je parle, nous parlons",
      "pointTitleZh": "词干 + 词尾：je parle，nous parlons",
      "anchor": "ex-e02-e02-1-1",
      "fr": "Nous aimons le café."
    },
    {
      "chapterId": "e02",
      "chapterTitleEn": "The present tense of -er verbs",
      "chapterTitleZh": "-er 动词的现在时",
      "pointTitleEn": "Negation: ne … pas",
      "pointTitleZh": "否定：ne … pas",
      "anchor": "ex-e02-e02-3-1",
      "fr": "Il n'aime pas le café."
    }
  ],
  "chat": [
    {
      "chapterId": "e01",
      "chapterTitleEn": "Gender & articles: le, la, un, une",
      "chapterTitleZh": "阴阳性与冠词：le、la、un、une",
      "pointTitleEn": "Every noun has a gender — le and la",
      "pointTitleZh": "每个名词都有性别 —— le 与 la",
      "anchor": "ex-e01-e01-1-0",
      "fr": "Le chat est noir."
    },
    {
      "chapterId": "e02",
      "chapterTitleEn": "The present tense of -er verbs",
      "chapterTitleZh": "-er 动词的现在时",
      "pointTitleEn": "j' before a vowel",
      "pointTitleZh": "元音前的 j'",
      "anchor": "ex-e02-e02-2-0",
      "fr": "J'aime le chat."
    }
  ],
  "enfant": [
    {
      "chapterId": "e01",
      "chapterTitleEn": "Gender & articles: le, la, un, une",
      "chapterTitleZh": "阴阳性与冠词：le、la、un、une",
      "pointTitleEn": "Before a vowel: l'",
      "pointTitleZh": "元音前：l'",
      "anchor": "ex-e01-e01-2-0",
      "fr": "L'enfant est petit."
    }
  ],
  "être": [
    {
      "chapterId": "e01",
      "chapterTitleEn": "Gender & articles: le, la, un, une",
      "chapterTitleZh": "阴阳性与冠词：le、la、un、une",
      "pointTitleEn": "Every noun has a gender — le and la",
      "pointTitleZh": "每个名词都有性别 —— le 与 la",
      "anchor": "ex-e01-e01-1-0",
      "fr": "Le chat est noir."
    },
    {
      "chapterId": "e01",
      "chapterTitleEn": "Gender & articles: le, la, un, une",
      "chapterTitleZh": "阴阳性与冠词：le、la、un、une",
      "pointTitleEn": "Every noun has a gender — le and la",
      "pointTitleZh": "每个名词都有性别 —— le 与 la",
      "anchor": "ex-e01-e01-1-1",
      "fr": "La voiture est grande."
    },
    {
      "chapterId": "e01",
      "chapterTitleEn": "Gender & articles: le, la, un, une",
      "chapterTitleZh": "阴阳性与冠词：le、la、un、une",
      "pointTitleEn": "Before a vowel: l'",
      "pointTitleZh": "元音前：l'",
      "anchor": "ex-e01-e01-2-0",
      "fr": "L'enfant est petit."
    },
    {
      "chapterId": "e01",
      "chapterTitleEn": "Gender & articles: le, la, un, une",
      "chapterTitleZh": "阴阳性与冠词：le、la、un、une",
      "pointTitleEn": "A, an: un and une",
      "pointTitleZh": "一个：un 与 une",
      "anchor": "ex-e01-e01-3-0",
      "fr": "Une pomme est rouge."
    }
  ],
  "grand": [
    {
      "chapterId": "e01",
      "chapterTitleEn": "Gender & articles: le, la, un, une",
      "chapterTitleZh": "阴阳性与冠词：le、la、un、une",
      "pointTitleEn": "Every noun has a gender — le and la",
      "pointTitleZh": "每个名词都有性别 —— le 与 la",
      "anchor": "ex-e01-e01-1-1",
      "fr": "La voiture est grande."
    }
  ],
  "noir": [
    {
      "chapterId": "e01",
      "chapterTitleEn": "Gender & articles: le, la, un, une",
      "chapterTitleZh": "阴阳性与冠词：le、la、un、une",
      "pointTitleEn": "Every noun has a gender — le and la",
      "pointTitleZh": "每个名词都有性别 —— le 与 la",
      "anchor": "ex-e01-e01-1-0",
      "fr": "Le chat est noir."
    }
  ],
  "parler": [
    {
      "chapterId": "e02",
      "chapterTitleEn": "The present tense of -er verbs",
      "chapterTitleZh": "-er 动词的现在时",
      "pointTitleEn": "Stem + ending: je parle, nous parlons",
      "pointTitleZh": "词干 + 词尾：je parle，nous parlons",
      "anchor": "ex-e02-e02-1-0",
      "fr": "Je parle français."
    },
    {
      "chapterId": "e02",
      "chapterTitleEn": "The present tense of -er verbs",
      "chapterTitleZh": "-er 动词的现在时",
      "pointTitleEn": "Negation: ne … pas",
      "pointTitleZh": "否定：ne … pas",
      "anchor": "ex-e02-e02-3-0",
      "fr": "Tu ne parles pas anglais."
    }
  ],
  "petit": [
    {
      "chapterId": "e01",
      "chapterTitleEn": "Gender & articles: le, la, un, une",
      "chapterTitleZh": "阴阳性与冠词：le、la、un、une",
      "pointTitleEn": "Before a vowel: l'",
      "pointTitleZh": "元音前：l'",
      "anchor": "ex-e01-e01-2-0",
      "fr": "L'enfant est petit."
    }
  ],
  "pomme": [
    {
      "chapterId": "e01",
      "chapterTitleEn": "Gender & articles: le, la, un, une",
      "chapterTitleZh": "阴阳性与冠词：le、la、un、une",
      "pointTitleEn": "A, an: un and une",
      "pointTitleZh": "一个：un 与 une",
      "anchor": "ex-e01-e01-3-0",
      "fr": "Une pomme est rouge."
    }
  ],
  "rouge": [
    {
      "chapterId": "e01",
      "chapterTitleEn": "Gender & articles: le, la, un, une",
      "chapterTitleZh": "阴阳性与冠词：le、la、un、une",
      "pointTitleEn": "A, an: un and une",
      "pointTitleZh": "一个：un 与 une",
      "anchor": "ex-e01-e01-3-0",
      "fr": "Une pomme est rouge."
    }
  ],
  "voiture": [
    {
      "chapterId": "e01",
      "chapterTitleEn": "Gender & articles: le, la, un, une",
      "chapterTitleZh": "阴阳性与冠词：le、la、un、une",
      "pointTitleEn": "Every noun has a gender — le and la",
      "pointTitleZh": "每个名词都有性别 —— le 与 la",
      "anchor": "ex-e01-e01-1-1",
      "fr": "La voiture est grande."
    }
  ]
};
