// AUTO-GENERATED by scripts/gen-reverse-index.mjs — DO NOT EDIT.
// Reverse index: vocab word → tutorial example sentences that reference it.
// Regenerated on every `pnpm build` / `pnpm dev`.

import type { ExampleRef } from "./types";

export const REVERSE_INDEX: Record<string, ExampleRef[]> = {
  "aimer": [
    {
      "chapterId": "e02",
      "chapterTitleEn": "The present tense of -er verbs",
      "chapterTitleZh": "-er 动词的现在时",
      "pointTitleEn": "Stem + ending: je parle, nous parlons",
      "pointTitleZh": "词干 + 词尾：je parle，nous parlons",
      "anchor": "ex-e02-e02-1-1",
      "fr": "Nous aimons le café."
    },
    {
      "chapterId": "e02",
      "chapterTitleEn": "The present tense of -er verbs",
      "chapterTitleZh": "-er 动词的现在时",
      "pointTitleEn": "j' before a vowel",
      "pointTitleZh": "元音前的 j'",
      "anchor": "ex-e02-e02-2-0",
      "fr": "J'aime le chat."
    },
    {
      "chapterId": "e02",
      "chapterTitleEn": "The present tense of -er verbs",
      "chapterTitleZh": "-er 动词的现在时",
      "pointTitleEn": "Negation: ne … pas",
      "pointTitleZh": "否定：ne … pas",
      "anchor": "ex-e02-e02-3-1",
      "fr": "Il n'aime pas le café."
    },
    {
      "chapterId": "e05",
      "chapterTitleEn": "Asking questions: est-ce que & rising intonation",
      "chapterTitleZh": "提问：est-ce que 与升调",
      "pointTitleEn": "The all-purpose tag: est-ce que",
      "pointTitleZh": "万能标签：est-ce que",
      "anchor": "ex-e05-e05-2-1",
      "fr": "Est-ce qu'il aime le café ?"
    },
    {
      "chapterId": "e05",
      "chapterTitleEn": "Asking questions: est-ce que & rising intonation",
      "chapterTitleZh": "提问：est-ce que 与升调",
      "pointTitleEn": "What NOT to do: the English inversion habit",
      "pointTitleZh": "不要做的事：英语的倒装习惯",
      "anchor": "ex-e05-e05-3-0",
      "fr": "Tu aimes le chat ?"
    },
    {
      "chapterId": "e05",
      "chapterTitleEn": "Asking questions: est-ce que & rising intonation",
      "chapterTitleZh": "提问：est-ce que 与升调",
      "pointTitleEn": "What NOT to do: the English inversion habit",
      "pointTitleZh": "不要做的事：英语的倒装习惯",
      "anchor": "ex-e05-e05-3-1",
      "fr": "Est-ce que tu aimes le chat ?"
    }
  ],
  "ami": [
    {
      "chapterId": "e03",
      "chapterTitleEn": "Plural nouns & des",
      "chapterTitleZh": "复数名词与 des",
      "pointTitleEn": "Some: des",
      "pointTitleZh": "一些：des",
      "anchor": "ex-e03-e03-2-0",
      "fr": "Des amis sont heureux."
    }
  ],
  "attendre": [
    {
      "chapterId": "e06",
      "chapterTitleEn": "-ir & -re verbs",
      "chapterTitleZh": "-ir 与 -re 动词",
      "pointTitleEn": "Third group: -re verbs and the silent il",
      "pointTitleZh": "第三组：-re 动词与沉默的 il",
      "anchor": "ex-e06-e06-2-1",
      "fr": "La femme attend le chat."
    }
  ],
  "avoir": [
    {
      "chapterId": "e04",
      "chapterTitleEn": "être & avoir",
      "chapterTitleZh": "être 与 avoir",
      "pointTitleEn": "avoir (to have): j'ai, tu as, il a",
      "pointTitleZh": "avoir（有）：j'ai、tu as、il a",
      "anchor": "ex-e04-e04-2-0",
      "fr": "J'ai un chat."
    },
    {
      "chapterId": "e04",
      "chapterTitleEn": "être & avoir",
      "chapterTitleZh": "être 与 avoir",
      "pointTitleEn": "avoir (to have): j'ai, tu as, il a",
      "pointTitleZh": "avoir（有）：j'ai、tu as、il a",
      "anchor": "ex-e04-e04-2-1",
      "fr": "Vous avez une voiture."
    },
    {
      "chapterId": "e04",
      "chapterTitleEn": "être & avoir",
      "chapterTitleZh": "être 与 avoir",
      "pointTitleEn": "avoir for age and hunger: j'ai … ans, j'ai faim",
      "pointTitleZh": "用 avoir 表年龄和饥饿：j'ai … ans、j'ai faim",
      "anchor": "ex-e04-e04-3-0",
      "fr": "J'ai vingt ans."
    },
    {
      "chapterId": "e04",
      "chapterTitleEn": "être & avoir",
      "chapterTitleZh": "être 与 avoir",
      "pointTitleEn": "avoir for age and hunger: j'ai … ans, j'ai faim",
      "pointTitleZh": "用 avoir 表年龄和饥饿：j'ai … ans、j'ai faim",
      "anchor": "ex-e04-e04-3-1",
      "fr": "J'ai faim."
    }
  ],
  "café": [
    {
      "chapterId": "e02",
      "chapterTitleEn": "The present tense of -er verbs",
      "chapterTitleZh": "-er 动词的现在时",
      "pointTitleEn": "Stem + ending: je parle, nous parlons",
      "pointTitleZh": "词干 + 词尾：je parle，nous parlons",
      "anchor": "ex-e02-e02-1-1",
      "fr": "Nous aimons le café."
    },
    {
      "chapterId": "e02",
      "chapterTitleEn": "The present tense of -er verbs",
      "chapterTitleZh": "-er 动词的现在时",
      "pointTitleEn": "Negation: ne … pas",
      "pointTitleZh": "否定：ne … pas",
      "anchor": "ex-e02-e02-3-1",
      "fr": "Il n'aime pas le café."
    },
    {
      "chapterId": "e05",
      "chapterTitleEn": "Asking questions: est-ce que & rising intonation",
      "chapterTitleZh": "提问：est-ce que 与升调",
      "pointTitleEn": "The all-purpose tag: est-ce que",
      "pointTitleZh": "万能标签：est-ce que",
      "anchor": "ex-e05-e05-2-1",
      "fr": "Est-ce qu'il aime le café ?"
    },
    {
      "chapterId": "e06",
      "chapterTitleEn": "-ir & -re verbs",
      "chapterTitleZh": "-ir 与 -re 动词",
      "pointTitleEn": "Putting them to work: questions and negation",
      "pointTitleZh": "投入使用：提问与否定",
      "anchor": "ex-e06-e06-3-0",
      "fr": "Je ne finis pas le café."
    }
  ],
  "chat": [
    {
      "chapterId": "e01",
      "chapterTitleEn": "Gender & articles: le, la, un, une",
      "chapterTitleZh": "阴阳性与冠词：le、la、un、une",
      "pointTitleEn": "Every noun has a gender — le and la",
      "pointTitleZh": "每个名词都有性别 —— le 与 la",
      "anchor": "ex-e01-e01-1-0",
      "fr": "Le chat est noir."
    },
    {
      "chapterId": "e02",
      "chapterTitleEn": "The present tense of -er verbs",
      "chapterTitleZh": "-er 动词的现在时",
      "pointTitleEn": "j' before a vowel",
      "pointTitleZh": "元音前的 j'",
      "anchor": "ex-e02-e02-2-0",
      "fr": "J'aime le chat."
    },
    {
      "chapterId": "e03",
      "chapterTitleEn": "Plural nouns & des",
      "chapterTitleZh": "复数名词与 des",
      "pointTitleEn": "Adjectives agree in the plural too",
      "pointTitleZh": "形容词在复数里也要一致",
      "anchor": "ex-e03-e03-3-0",
      "fr": "Les chats sont noirs."
    },
    {
      "chapterId": "e04",
      "chapterTitleEn": "être & avoir",
      "chapterTitleZh": "être 与 avoir",
      "pointTitleEn": "avoir (to have): j'ai, tu as, il a",
      "pointTitleZh": "avoir（有）：j'ai、tu as、il a",
      "anchor": "ex-e04-e04-2-0",
      "fr": "J'ai un chat."
    },
    {
      "chapterId": "e05",
      "chapterTitleEn": "Asking questions: est-ce que & rising intonation",
      "chapterTitleZh": "提问：est-ce que 与升调",
      "pointTitleEn": "What NOT to do: the English inversion habit",
      "pointTitleZh": "不要做的事：英语的倒装习惯",
      "anchor": "ex-e05-e05-3-0",
      "fr": "Tu aimes le chat ?"
    },
    {
      "chapterId": "e05",
      "chapterTitleEn": "Asking questions: est-ce que & rising intonation",
      "chapterTitleZh": "提问：est-ce que 与升调",
      "pointTitleEn": "What NOT to do: the English inversion habit",
      "pointTitleZh": "不要做的事：英语的倒装习惯",
      "anchor": "ex-e05-e05-3-1",
      "fr": "Est-ce que tu aimes le chat ?"
    },
    {
      "chapterId": "e06",
      "chapterTitleEn": "-ir & -re verbs",
      "chapterTitleZh": "-ir 与 -re 动词",
      "pointTitleEn": "Third group: -re verbs and the silent il",
      "pointTitleZh": "第三组：-re 动词与沉默的 il",
      "anchor": "ex-e06-e06-2-1",
      "fr": "La femme attend le chat."
    }
  ],
  "choisir": [
    {
      "chapterId": "e06",
      "chapterTitleEn": "-ir & -re verbs",
      "chapterTitleZh": "-ir 与 -re 动词",
      "pointTitleEn": "Second group: -ir verbs and the -iss- surprise",
      "pointTitleZh": "第二组：-ir 动词与 -iss- 惊喜",
      "anchor": "ex-e06-e06-1-1",
      "fr": "Nous choisissons une pomme."
    }
  ],
  "enfant": [
    {
      "chapterId": "e01",
      "chapterTitleEn": "Gender & articles: le, la, un, une",
      "chapterTitleZh": "阴阳性与冠词：le、la、un、une",
      "pointTitleEn": "Before a vowel: l'",
      "pointTitleZh": "元音前：l'",
      "anchor": "ex-e01-e01-2-0",
      "fr": "L'enfant est petit."
    }
  ],
  "être": [
    {
      "chapterId": "e01",
      "chapterTitleEn": "Gender & articles: le, la, un, une",
      "chapterTitleZh": "阴阳性与冠词：le、la、un、une",
      "pointTitleEn": "Every noun has a gender — le and la",
      "pointTitleZh": "每个名词都有性别 —— le 与 la",
      "anchor": "ex-e01-e01-1-0",
      "fr": "Le chat est noir."
    },
    {
      "chapterId": "e01",
      "chapterTitleEn": "Gender & articles: le, la, un, une",
      "chapterTitleZh": "阴阳性与冠词：le、la、un、une",
      "pointTitleEn": "Every noun has a gender — le and la",
      "pointTitleZh": "每个名词都有性别 —— le 与 la",
      "anchor": "ex-e01-e01-1-1",
      "fr": "La voiture est grande."
    },
    {
      "chapterId": "e01",
      "chapterTitleEn": "Gender & articles: le, la, un, une",
      "chapterTitleZh": "阴阳性与冠词：le、la、un、une",
      "pointTitleEn": "Before a vowel: l'",
      "pointTitleZh": "元音前：l'",
      "anchor": "ex-e01-e01-2-0",
      "fr": "L'enfant est petit."
    },
    {
      "chapterId": "e01",
      "chapterTitleEn": "Gender & articles: le, la, un, une",
      "chapterTitleZh": "阴阳性与冠词：le、la、un、une",
      "pointTitleEn": "A, an: un and une",
      "pointTitleZh": "一个：un 与 une",
      "anchor": "ex-e01-e01-3-0",
      "fr": "Une pomme est rouge."
    },
    {
      "chapterId": "e03",
      "chapterTitleEn": "Plural nouns & des",
      "chapterTitleZh": "复数名词与 des",
      "pointTitleEn": "Add -s, and one article for all: les",
      "pointTitleZh": "加 -s，一个冠词通吃：les",
      "anchor": "ex-e03-e03-1-0",
      "fr": "Les livres sont petits."
    },
    {
      "chapterId": "e03",
      "chapterTitleEn": "Plural nouns & des",
      "chapterTitleZh": "复数名词与 des",
      "pointTitleEn": "Add -s, and one article for all: les",
      "pointTitleZh": "加 -s，一个冠词通吃：les",
      "anchor": "ex-e03-e03-1-1",
      "fr": "Les journaux sont français."
    },
    {
      "chapterId": "e03",
      "chapterTitleEn": "Plural nouns & des",
      "chapterTitleZh": "复数名词与 des",
      "pointTitleEn": "Some: des",
      "pointTitleZh": "一些：des",
      "anchor": "ex-e03-e03-2-0",
      "fr": "Des amis sont heureux."
    },
    {
      "chapterId": "e03",
      "chapterTitleEn": "Plural nouns & des",
      "chapterTitleZh": "复数名词与 des",
      "pointTitleEn": "Adjectives agree in the plural too",
      "pointTitleZh": "形容词在复数里也要一致",
      "anchor": "ex-e03-e03-3-0",
      "fr": "Les chats sont noirs."
    },
    {
      "chapterId": "e03",
      "chapterTitleEn": "Plural nouns & des",
      "chapterTitleZh": "复数名词与 des",
      "pointTitleEn": "Adjectives agree in the plural too",
      "pointTitleZh": "形容词在复数里也要一致",
      "anchor": "ex-e03-e03-3-1",
      "fr": "Les voitures sont grandes."
    },
    {
      "chapterId": "e04",
      "chapterTitleEn": "être & avoir",
      "chapterTitleZh": "être 与 avoir",
      "pointTitleEn": "être (to be): je suis, tu es, il est",
      "pointTitleZh": "être（是）：je suis、tu es、il est",
      "anchor": "ex-e04-e04-1-0",
      "fr": "Je suis étudiant."
    },
    {
      "chapterId": "e04",
      "chapterTitleEn": "être & avoir",
      "chapterTitleZh": "être 与 avoir",
      "pointTitleEn": "être (to be): je suis, tu es, il est",
      "pointTitleZh": "être（是）：je suis、tu es、il est",
      "anchor": "ex-e04-e04-1-1",
      "fr": "Nous sommes français."
    }
  ],
  "femme": [
    {
      "chapterId": "e06",
      "chapterTitleEn": "-ir & -re verbs",
      "chapterTitleZh": "-ir 与 -re 动词",
      "pointTitleEn": "Third group: -re verbs and the silent il",
      "pointTitleZh": "第三组：-re 动词与沉默的 il",
      "anchor": "ex-e06-e06-2-1",
      "fr": "La femme attend le chat."
    }
  ],
  "finir": [
    {
      "chapterId": "e06",
      "chapterTitleEn": "-ir & -re verbs",
      "chapterTitleZh": "-ir 与 -re 动词",
      "pointTitleEn": "Second group: -ir verbs and the -iss- surprise",
      "pointTitleZh": "第二组：-ir 动词与 -iss- 惊喜",
      "anchor": "ex-e06-e06-1-0",
      "fr": "Je finis le pain."
    },
    {
      "chapterId": "e06",
      "chapterTitleEn": "-ir & -re verbs",
      "chapterTitleZh": "-ir 与 -re 动词",
      "pointTitleEn": "Putting them to work: questions and negation",
      "pointTitleZh": "投入使用：提问与否定",
      "anchor": "ex-e06-e06-3-0",
      "fr": "Je ne finis pas le café."
    }
  ],
  "français": [
    {
      "chapterId": "e03",
      "chapterTitleEn": "Plural nouns & des",
      "chapterTitleZh": "复数名词与 des",
      "pointTitleEn": "Add -s, and one article for all: les",
      "pointTitleZh": "加 -s，一个冠词通吃：les",
      "anchor": "ex-e03-e03-1-1",
      "fr": "Les journaux sont français."
    }
  ],
  "grand": [
    {
      "chapterId": "e01",
      "chapterTitleEn": "Gender & articles: le, la, un, une",
      "chapterTitleZh": "阴阳性与冠词：le、la、un、une",
      "pointTitleEn": "Every noun has a gender — le and la",
      "pointTitleZh": "每个名词都有性别 —— le 与 la",
      "anchor": "ex-e01-e01-1-1",
      "fr": "La voiture est grande."
    },
    {
      "chapterId": "e03",
      "chapterTitleEn": "Plural nouns & des",
      "chapterTitleZh": "复数名词与 des",
      "pointTitleEn": "Adjectives agree in the plural too",
      "pointTitleZh": "形容词在复数里也要一致",
      "anchor": "ex-e03-e03-3-1",
      "fr": "Les voitures sont grandes."
    }
  ],
  "habiter": [
    {
      "chapterId": "e05",
      "chapterTitleEn": "Asking questions: est-ce que & rising intonation",
      "chapterTitleZh": "提问：est-ce que 与升调",
      "pointTitleEn": "Just raise your voice: the intonation question",
      "pointTitleZh": "只需提高声调：升调疑问句",
      "anchor": "ex-e05-e05-1-1",
      "fr": "Vous habitez ici ?"
    }
  ],
  "heureux": [
    {
      "chapterId": "e03",
      "chapterTitleEn": "Plural nouns & des",
      "chapterTitleZh": "复数名词与 des",
      "pointTitleEn": "Some: des",
      "pointTitleZh": "一些：des",
      "anchor": "ex-e03-e03-2-0",
      "fr": "Des amis sont heureux."
    }
  ],
  "journal": [
    {
      "chapterId": "e03",
      "chapterTitleEn": "Plural nouns & des",
      "chapterTitleZh": "复数名词与 des",
      "pointTitleEn": "Add -s, and one article for all: les",
      "pointTitleZh": "加 -s，一个冠词通吃：les",
      "anchor": "ex-e03-e03-1-1",
      "fr": "Les journaux sont français."
    }
  ],
  "livre": [
    {
      "chapterId": "e03",
      "chapterTitleEn": "Plural nouns & des",
      "chapterTitleZh": "复数名词与 des",
      "pointTitleEn": "Add -s, and one article for all: les",
      "pointTitleZh": "加 -s，一个冠词通吃：les",
      "anchor": "ex-e03-e03-1-0",
      "fr": "Les livres sont petits."
    }
  ],
  "maison": [
    {
      "chapterId": "e06",
      "chapterTitleEn": "-ir & -re verbs",
      "chapterTitleZh": "-ir 与 -re 动词",
      "pointTitleEn": "Putting them to work: questions and negation",
      "pointTitleZh": "投入使用：提问与否定",
      "anchor": "ex-e06-e06-3-1",
      "fr": "Est-ce que tu vends la maison ?"
    }
  ],
  "noir": [
    {
      "chapterId": "e01",
      "chapterTitleEn": "Gender & articles: le, la, un, une",
      "chapterTitleZh": "阴阳性与冠词：le、la、un、une",
      "pointTitleEn": "Every noun has a gender — le and la",
      "pointTitleZh": "每个名词都有性别 —— le 与 la",
      "anchor": "ex-e01-e01-1-0",
      "fr": "Le chat est noir."
    },
    {
      "chapterId": "e03",
      "chapterTitleEn": "Plural nouns & des",
      "chapterTitleZh": "复数名词与 des",
      "pointTitleEn": "Adjectives agree in the plural too",
      "pointTitleZh": "形容词在复数里也要一致",
      "anchor": "ex-e03-e03-3-0",
      "fr": "Les chats sont noirs."
    }
  ],
  "pain": [
    {
      "chapterId": "e06",
      "chapterTitleEn": "-ir & -re verbs",
      "chapterTitleZh": "-ir 与 -re 动词",
      "pointTitleEn": "Second group: -ir verbs and the -iss- surprise",
      "pointTitleZh": "第二组：-ir 动词与 -iss- 惊喜",
      "anchor": "ex-e06-e06-1-0",
      "fr": "Je finis le pain."
    }
  ],
  "parler": [
    {
      "chapterId": "e02",
      "chapterTitleEn": "The present tense of -er verbs",
      "chapterTitleZh": "-er 动词的现在时",
      "pointTitleEn": "Stem + ending: je parle, nous parlons",
      "pointTitleZh": "词干 + 词尾：je parle，nous parlons",
      "anchor": "ex-e02-e02-1-0",
      "fr": "Je parle français."
    },
    {
      "chapterId": "e02",
      "chapterTitleEn": "The present tense of -er verbs",
      "chapterTitleZh": "-er 动词的现在时",
      "pointTitleEn": "Negation: ne … pas",
      "pointTitleZh": "否定：ne … pas",
      "anchor": "ex-e02-e02-3-0",
      "fr": "Tu ne parles pas anglais."
    },
    {
      "chapterId": "e05",
      "chapterTitleEn": "Asking questions: est-ce que & rising intonation",
      "chapterTitleZh": "提问：est-ce que 与升调",
      "pointTitleEn": "Just raise your voice: the intonation question",
      "pointTitleZh": "只需提高声调：升调疑问句",
      "anchor": "ex-e05-e05-1-0",
      "fr": "Tu parles français ?"
    },
    {
      "chapterId": "e05",
      "chapterTitleEn": "Asking questions: est-ce que & rising intonation",
      "chapterTitleZh": "提问：est-ce que 与升调",
      "pointTitleEn": "The all-purpose tag: est-ce que",
      "pointTitleZh": "万能标签：est-ce que",
      "anchor": "ex-e05-e05-2-0",
      "fr": "Est-ce que tu parles anglais ?"
    }
  ],
  "petit": [
    {
      "chapterId": "e01",
      "chapterTitleEn": "Gender & articles: le, la, un, une",
      "chapterTitleZh": "阴阳性与冠词：le、la、un、une",
      "pointTitleEn": "Before a vowel: l'",
      "pointTitleZh": "元音前：l'",
      "anchor": "ex-e01-e01-2-0",
      "fr": "L'enfant est petit."
    },
    {
      "chapterId": "e03",
      "chapterTitleEn": "Plural nouns & des",
      "chapterTitleZh": "复数名词与 des",
      "pointTitleEn": "Add -s, and one article for all: les",
      "pointTitleZh": "加 -s，一个冠词通吃：les",
      "anchor": "ex-e03-e03-1-0",
      "fr": "Les livres sont petits."
    }
  ],
  "pomme": [
    {
      "chapterId": "e01",
      "chapterTitleEn": "Gender & articles: le, la, un, une",
      "chapterTitleZh": "阴阳性与冠词：le、la、un、une",
      "pointTitleEn": "A, an: un and une",
      "pointTitleZh": "一个：un 与 une",
      "anchor": "ex-e01-e01-3-0",
      "fr": "Une pomme est rouge."
    },
    {
      "chapterId": "e06",
      "chapterTitleEn": "-ir & -re verbs",
      "chapterTitleZh": "-ir 与 -re 动词",
      "pointTitleEn": "Second group: -ir verbs and the -iss- surprise",
      "pointTitleZh": "第二组：-ir 动词与 -iss- 惊喜",
      "anchor": "ex-e06-e06-1-1",
      "fr": "Nous choisissons une pomme."
    }
  ],
  "rouge": [
    {
      "chapterId": "e01",
      "chapterTitleEn": "Gender & articles: le, la, un, une",
      "chapterTitleZh": "阴阳性与冠词：le、la、un、une",
      "pointTitleEn": "A, an: un and une",
      "pointTitleZh": "一个：un 与 une",
      "anchor": "ex-e01-e01-3-0",
      "fr": "Une pomme est rouge."
    }
  ],
  "vendre": [
    {
      "chapterId": "e06",
      "chapterTitleEn": "-ir & -re verbs",
      "chapterTitleZh": "-ir 与 -re 动词",
      "pointTitleEn": "Third group: -re verbs and the silent il",
      "pointTitleZh": "第三组：-re 动词与沉默的 il",
      "anchor": "ex-e06-e06-2-0",
      "fr": "Je vends la voiture."
    },
    {
      "chapterId": "e06",
      "chapterTitleEn": "-ir & -re verbs",
      "chapterTitleZh": "-ir 与 -re 动词",
      "pointTitleEn": "Putting them to work: questions and negation",
      "pointTitleZh": "投入使用：提问与否定",
      "anchor": "ex-e06-e06-3-1",
      "fr": "Est-ce que tu vends la maison ?"
    }
  ],
  "voiture": [
    {
      "chapterId": "e01",
      "chapterTitleEn": "Gender & articles: le, la, un, une",
      "chapterTitleZh": "阴阳性与冠词：le、la、un、une",
      "pointTitleEn": "Every noun has a gender — le and la",
      "pointTitleZh": "每个名词都有性别 —— le 与 la",
      "anchor": "ex-e01-e01-1-1",
      "fr": "La voiture est grande."
    },
    {
      "chapterId": "e03",
      "chapterTitleEn": "Plural nouns & des",
      "chapterTitleZh": "复数名词与 des",
      "pointTitleEn": "Adjectives agree in the plural too",
      "pointTitleZh": "形容词在复数里也要一致",
      "anchor": "ex-e03-e03-3-1",
      "fr": "Les voitures sont grandes."
    },
    {
      "chapterId": "e04",
      "chapterTitleEn": "être & avoir",
      "chapterTitleZh": "être 与 avoir",
      "pointTitleEn": "avoir (to have): j'ai, tu as, il a",
      "pointTitleZh": "avoir（有）：j'ai、tu as、il a",
      "anchor": "ex-e04-e04-2-1",
      "fr": "Vous avez une voiture."
    },
    {
      "chapterId": "e06",
      "chapterTitleEn": "-ir & -re verbs",
      "chapterTitleZh": "-ir 与 -re 动词",
      "pointTitleEn": "Third group: -re verbs and the silent il",
      "pointTitleZh": "第三组：-re 动词与沉默的 il",
      "anchor": "ex-e06-e06-2-0",
      "fr": "Je vends la voiture."
    }
  ]
};
